CUSTOM_TEMPLATES = {
    # "OxfordPets": "a photo of a {}, a type of pet.",
    "OxfordPets": ["a photo of a {}, a type of pet.",
                "a picture of a {}, a type of pet.",
                "an image of a {}, a type of pet.",
                "a photo of a pet, classified as {}.",
                "a photo of a pet, categorized as {}.",
                "a photo of a pet, labeled as {}.",
                "a picture of a pet, classified as {}.",
                "a picture of a pet, categorized as {}.",
                "a picture of a pet, labeled as {}.",
                "an image of a pet, classified as {}.",
                "an image of a pet, categorized as {}.",
                "an image of a pet, labeled as {}."],

    # "OxfordFlowers": "a photo of a {}, a type of flower.",
    "OxfordFlowers": ["a photo of a {}, a type of flower.",
                      "a picture of a {}, a type of flower.",
                      "an image of a {}, a type of flower.",
                      "a photo of a flower, classified as {}.",
                      "a photo of a flower, categorized as {}.",
                      "a photo of a flower, labeled as {}.",
                      "a picture of a flower, classified as {}.",
                      "a picture of a flower, categorized as {}.",
                      "a picture of a flower, labeled as {}.",
                      "an image of a flower, classified as {}.",
                      "an image of a flower, categorized as {}.",
                      "an image of a flower, labeled as {}."],
    # "FGVCAircraft": "a photo of a {}, a type of aircraft.",
    "FGVCAircraft": ["a photo of a {}, a type of aircraft.",
                    "a picture of a {}, a type of aircraft.",
                    "an image of a {}, a type of aircraft.",
                    "a photo of a aircraft, classified as {}.",
                    "a photo of a aircraft, categorized as {}.",
                    "a photo of a aircraft, labeled as {}.",
                    "a picture of a aircraft, classified as {}.",
                    "a picture of a aircraft, categorized as {}.",
                    "a picture of a aircraft, labeled as {}.",
                    "an image of a aircraft, classified as {}.",
                    "an image of a aircraft, categorized as {}.",
                    "an image of a aircraft, labeled as {}."],
    # "DescribableTextures": "a photo of {}, a type of texture.",
    "DescribableTextures": ["a photo of {}, a type of texture.",
                            "a picture of {}, a type of texture.",
                             "an image of {}, a type of texture.",
                            "a photo of a texture, classified as {}.",
                            "a photo of a texture, categorized as {}.",
                            "a photo of a texture, labeled as {}.",
                            "a picture of a texture, classified as {}.",
                            "a picture of a texture, categorized as {}.",
                            "a picture of a texture, labeled as {}.",
                            "an image of a texture, classified as {}.",
                            "an image of a texture, categorized as {}.",
                            "an image of a texture, labeled as {}.",],
    # "DescribableTextures": ["a photo of {}, a type of texture.",
    #                         "{}texture.",
    #                         "a photo of {}.",
    #                         "In the whispering forest, a {} dreams of stars.",],
    
    # "EuroSAT": "a centered satellite photo of {}.",
    "EuroSAT": ["a centered satellite photo of {}.",
                "a centered satellite picture of {}.",
                "a centered satellite image of {}.",
                "a centered satellite photo, classified as {}.",
                "a centered satellite photo, categorized as {}.",
                "a centered satellite photo, labeled as {}.",
                "a centered satellite picture, classified as {}.",
                "a centered satellite picture, categorized as {}.",
                "a centered satellite picture, labeled as {}.",
                "a centered satellite image, classified as {}.",
                "a centered satellite image, categorized as {}.",
                "a centered satellite image, labeled as {}."],

    # "StanfordCars": "a photo of a {}.",
    "StanfordCars":["a photo of a {}.",
            "a picture of a {}.",
            "an image of a {}.",
            "a photo, classified as {}.",
            "a photo, categorized as {}.",
            "a photo, labeled as {}.",
            "a picture, classified as {}.",
            "a picture, categorized as {}.",
            "a picture, labeled as {}.",
            "an image, classified as {}.",
            "an image, categorized as {}.",
            "an image, labeled as {}."],
    # "Food101": "a photo of {}, a type of food.",
    "Food101": ["a photo of {}, a type of food.",
            "a picture of {}, a type of food.",
            "an image of {}, a type of food.",
            "a photo of food, classified as {}.",
            "a photo of food, categorized as {}.",
            "a photo of food, labeled as {}.",
            "a picture of food, classified as {}.",
            "a picture of food, categorized as {}.",
            "a picture of food, labeled as {}.",
            "an image of food, classified as {}.",
            "an image of food, categorized as {}.",
            "an image of food, labeled as {}."],
    # "SUN397": "a photo of a {}.",
    "SUN397":["a photo of a {}.",
        "a picture of a {}.",
        "an image of a {}.",
        "a photo, classified as {}.",
        "a photo, categorized as {}.",
        "a photo, labeled as {}.",
        "a picture, classified as {}.",
        "a picture, categorized as {}.",
        "a picture, labeled as {}.",
        "an image, classified as {}.",
        "an image, categorized as {}.",
        "an image, labeled as {}."],
    # "Caltech101": "a photo of a {}.",
    "Caltech101":["a photo of a {}.",
                "a picture of a {}.",
                "an image of a {}.",
                "a photo, classified as {}.",
                "a photo, categorized as {}.",
                "a photo, labeled as {}.",
                "a picture, classified as {}.",
                "a picture, categorized as {}.",
                "a picture, labeled as {}.",
                "an image, classified as {}.",
                "an image, categorized as {}.",
                "an image, labeled as {}."],
    # "UCF101": "a photo of a person doing {}.",
    "UCF101":  ["a photo of a person doing {}.",
            "a picture of a person doing {}.",
            "an image of a person doing {}.",
            "a photo of a person doing, classified as {}.",
            "a photo of a person doing, categorized as {}.",
            "a photo of a person doing, labeled as {}.",
            "a picture of a person doing, classified as {}.",
            "a picture of a person doing, categorized as {}.",
            "a picture of a person doing, labeled as {}.",
            "an image of a person doing, classified as {}.",
            "an image of a person doing, categorized as {}.",
            "an image of a person doing, labeled as {}."],
    # "ImageNet": "a photo of a {}.",
    "ImageNet":["a photo of a {}.",
            "a picture of a {}.",
            "an image of a {}.",
            "a photo, classified as {}.",
            "a photo, categorized as {}.",
            "a photo, labeled as {}.",
            "a picture, classified as {}.",
            "a picture, categorized as {}.",
            "a picture, labeled as {}.",
            "an image, classified as {}.",
            "an image, categorized as {}.",
            "an image, labeled as {}."],
    "ImageNetSketch": "a photo of a {}.",
    "ImageNetV2": "a photo of a {}.",
    "ImageNetA": "a photo of a {}.",
    "ImageNetR": "a photo of a {}.",               
}

#The mixture of task-related and task-unrelated hard prompt pool
LASP_PROMPTS = [
    "a photo of a {}, a type of flower.",
    "a photo of a person doing {}.",
    "a centered satellite photo of {}.",
    "a photo of a {}, a type of aircraft.",
    "{} texture.",
    "itap of a {}.",
    "a bad photo of the {}.",
    "a origami {}.",
    "a photo of the large {}.",
    "a {} in a video game.",
    "art of the {}.",
    "a photo of the small {}.",
    "a photo of a {}.",
    "a photo of many {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a pixelated photo of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a close-up photo of the {}.",
    "a low resolution photo of a {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a blurry photo of a {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
    "a jpeg corrupted photo of the {}.",
    "a good photo of a {}.",
    ]
NOISY_PROMPTS = [
                ##Group A
                "a collection of {} floating in the sky",
                "{} wrapped in a mysterious bubble",
                "an unexpected encounter with a {}",
                "a {} hidden among the stars",
                "a vibrant dance of the {}",
                "the laughter of a {} echoing through the forest",
                "a {} emerging from the depths of the ocean",
                "a journey through the pages of a {}",
                "the whispers of a {} in the wind",
                "a {} perched on the edge of a cliff",
                "a {} illuminated by the moonlight",
                "the song of a {} resonating in the mountains",
                ##Group B
                # "Under the luminous sky, a {} dances with shadows.",
                # "In the whispering forest, a {} dreams of stars.",
                # "A {} floats in a teacup filled with stormy clouds.",
                # "With a melody of forgotten songs, a {} paints the sunrise.",
                # "A {} juggles moonbeams at the edge of twilight.",
                # "Inside a clockwork, a {} unravels the fabric of time.",
                # "Beneath the rainbow waterfall, a {} plays a silent tune.",
                # "A {} weaves dreams into the fabric of the cosmos.",
                # "In the heart of an ancient book, a {} discovers hidden worlds.",
                # "A {} dances on the petals of an upside-down flower.",
                # "Amongst the whispers of the wind, a {} listens to the earth's heartbeat.",
                # "A {} rides the waves of a sunbeam across the ocean of eternity.",
                ]
